function foldAll()
    org.netbeans.api.editor.fold.FoldUtilities.collapseAll(...
    org.netbeans.api.editor.fold.FoldHierarchy.get(com.mathworks. ...
    mlservices.MLEditorServices.getEditorApplication.getActiveEditor. ...
    getTextComponent()));
end